steps:

  # ! build
  # installation des dépendances joués sur cloud build
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    id: "Install"

    # ! test
    # TODO

    # ! deploy
    # TODO