steps:

  # ! build
  # installation des dépendances joués sur cloud build
  - name: install dépendances python
  # nom du programme en entrée
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    id: "Install"

    # ! test
  - name: test python code  
    entrypoint: python
    args: ["-m", "pytest" ]
    id: "Test"
    # TODO

    # ! deploy
    # TODO