name: 4.3 module example 1 CICD pipeline

#déclenchement du pipeline
#contrairement à GCP configurable d'ici
on:
  push:
    branches: ["main"]

#étapes du pipeline
jobs:

  #première étape qu'on peut nommer arbitrairement
    build:      
      #description du type de machine sur laquelle on veut run une étape
        runs-on: ubuntu-latest
      #détails de l'étape
        steps:
          # permet de cloner le dépot et de l'ouvrir (actions/checkout@v4 > nom de l'action)
            - uses: actions/checkout@v4
            - name: build-and-test
           # `run` avec le caractère `|` permet d'écrire plusieurs commandes à la suite
              run: |
                docker build -t new-image:latest -f Dockerfile .
                docker run new-image:latest bash -c "python -m pytest"
                
     # CONTINUOUS DEPLOYMENT
    push-image-to-gar:
      runs-on: ubuntu-latest
      # permet d'éviter les race conditions
      needs: build-and-test
      steps:
        - uses: actions/checkout@v4
        - name: se login au Google Artifact Registry
          uses: docker/login-action@v3
          with:
            registry: europe-west1-docker.pkg.dev
            username: _json_key
            password: ${{ secrets.CLOUD_RUN_DEPLOYER_SA_KEY }}
    
